import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export const AI_DISCLAIMER =
  "The content displayed in this document has been generated by artificial intelligence and is provided for " +
  "educational guidance purposes only. While every effort is made to ensure relevance and accuracy, AI-generated " +
  "content may contain errors or inaccuracies. The school and its affiliates make no warranties regarding the " +
  "completeness or fitness of this content for any specific purpose. Users are advised to review and verify all " +
  "content before use or distribution.";

/**
 * Captures the given element as a canvas and downloads it as a PDF.
 * @param contentEl  The DOM element whose content should be exported.
 * @param title      Document title shown at the top of the PDF (e.g. "Lesson Plan").
 * @param subtitle   Optional subtitle (e.g. topic / subject / grade string).
 */
export async function generateAiPdf(
  contentEl: HTMLElement,
  title: string,
  subtitle?: string,
): Promise<void> {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = margin;

  // ── Header ────────────────────────────────────────────────────────────────
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(30, 30, 30);
  pdf.text(title, margin, cursorY);
  cursorY += 7;

  if (subtitle) {
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(100, 100, 100);
    pdf.text(subtitle, margin, cursorY);
    cursorY += 6;
  }

  // Generation timestamp (right-aligned)
  const timestamp = new Date().toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text(`Generated: ${timestamp}`, pageWidth - margin, margin + 2, { align: "right" });

  // Divider
  cursorY += 2;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 5;

  // ── Content (html2canvas snapshot) ────────────────────────────────────────
  const canvas = await html2canvas(contentEl, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#ffffff",
    logging: false,
    onclone: (clonedDoc) => {
      // Strip dark mode so the PDF always renders with light-mode colours
      clonedDoc.documentElement.classList.remove("dark");
    },
  });

  const imgData = canvas.toDataURL("image/png");
  const imgHeightMm = (canvas.height / canvas.width) * contentWidth;

  // Handle multi-page content
  const availableHeight = pageHeight - cursorY - 30; // 30mm reserved for footer
  if (imgHeightMm <= availableHeight) {
    pdf.addImage(imgData, "PNG", margin, cursorY, contentWidth, imgHeightMm);
    cursorY += imgHeightMm + 8;
  } else {
    // Slice across pages
    let remainingHeight = imgHeightMm;
    let srcY = 0;
    let isFirstPage = true;

    while (remainingHeight > 0) {
      const slotHeight = isFirstPage ? availableHeight : pageHeight - 30 - margin;
      const sliceHeight = Math.min(remainingHeight, slotHeight);
      const sliceRatio = sliceHeight / imgHeightMm;
      const srcSliceHeight = canvas.height * sliceRatio;

      // Create a slice canvas
      const sliceCanvas = document.createElement("canvas");
      sliceCanvas.width = canvas.width;
      sliceCanvas.height = Math.round(srcSliceHeight);
      const ctx = sliceCanvas.getContext("2d")!;
      ctx.drawImage(
        canvas,
        0, Math.round(srcY * canvas.height / imgHeightMm),
        canvas.width, Math.round(srcSliceHeight),
        0, 0,
        canvas.width, Math.round(srcSliceHeight),
      );

      const sliceData = sliceCanvas.toDataURL("image/png");
      pdf.addImage(sliceData, "PNG", margin, isFirstPage ? cursorY : margin, contentWidth, sliceHeight);

      remainingHeight -= sliceHeight;
      srcY += sliceHeight;
      if (remainingHeight > 0) {
        pdf.addPage();
        isFirstPage = false;
      }
    }
  }

  // ── Footer: AI Disclaimer ─────────────────────────────────────────────────
  const totalPages: number = (pdf.internal as any).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    const footerY = pageHeight - 18;

    // Thin separator line
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, footerY - 3, pageWidth - margin, footerY - 3);

    // Disclaimer label
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(120, 120, 120);
    pdf.text("AI-GENERATED CONTENT DISCLAIMER", margin, footerY);

    // Disclaimer body (wrapped)
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(140, 140, 140);
    const disclaimerLines = pdf.splitTextToSize(AI_DISCLAIMER, contentWidth);
    pdf.text(disclaimerLines.slice(0, 3), margin, footerY + 4); // max 3 lines

    // Page number
    pdf.setFontSize(8);
    pdf.setTextColor(170, 170, 170);
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin, footerY, { align: "right" });
  }

  // ── Save ──────────────────────────────────────────────────────────────────
  const safeTitle = title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  pdf.save(`${safeTitle}_${Date.now()}.pdf`);
}
