import { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
    const schoolName = process.env.SCHOOL_NAME || 'School Management System';
    // Create a short name (max ~12 chars for home screen label)
    const shortName = schoolName.length > 12 ? schoolName.split(' ').slice(0, 2).join(' ') : schoolName;

    return {
        name: schoolName,
        short_name: shortName,
        description: `A comprehensive school management system for ${schoolName}.`,
        start_url: '/',
        display: 'standalone',
        background_color: '#1e3a5f',
        theme_color: '#1e3a5f',
        orientation: 'portrait-primary',
        scope: '/',
        lang: 'en',
        categories: ['education', 'productivity'],
        // Essential sizes only — generated by generate-pwa-icons.mjs
        icons: [
            { src: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: '/icons/icon-512x512.png', sizes: '512x512', type: 'image/png' },
            { src: '/icons/icon-maskable-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
        shortcuts: [
            {
                name: 'Dashboard',
                url: '/dashboard',
                description: 'Go to the admin dashboard',
                icons: [{ src: '/icons/icon-192x192.png', sizes: '192x192' }],
            },
            {
                name: 'Parent Portal',
                url: '/parent-dashboard',
                description: 'Go to the parent portal',
                icons: [{ src: '/icons/icon-192x192.png', sizes: '192x192' }],
            },
        ],
    };
}
